### ISSUE TITLE
Drop down menu

### ISSUE THREAD

**Issue by hldouglas** [hldouglas/dsn1674-project-3#1]
I've been attempting to create a responsive drop down menu. However, it's not been very responsive. I've attempted to use this website (http://fiddle.jshell.net/kmturley/04L0dkcj/10/show/#) to model the drop down menu from. I feel I might need to use something more than HTML and CSS to make it though.

**Comment by hldouglas** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
Have you watched my video tutorials on toggle menus?
http://learn-the-web.algonquindesign.ca/topics/navigation/
I tried to keep them really simple.

**Comment by hldouglas** [comment]
I did not. I have now, that is a lot simpler than what I was making.
