### ISSUE TITLE
Back to top link

### ISSUE THREAD

**Issue by hldouglas** [hldouglas/dsn1674-project-3#3]
I want to make my image in my footer a link back to the top of the page, but my attempts haven't been working.

**Comment by hldouglas** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
Have you tried putting it inside an `<a>` tag?

**Comment by hldouglas** [comment]
I did, put my coding could have been wrong when I tried it.

**Comment by hldouglas** [comment]
Figured out what I was doing wrong.
